### ISSUE TITLE
Melhorar Verificação dos Léxicos

### ISSUE THREAD

**Issue by matheuscvp** [Requisitos-de-Software/2021.2-AntennaPod#105]
## Descrição da Issue
Melhorar a verificação feita sobre o artefato léxicos.

## Tasks:
- [ ] Realizar a verificação de cada léxico
- [ ] Mostrar resultados gerais da verificação

## Critérios de Aceitação:
- [ ] Ter sido uma melhorar válida da verificação

## Assignees
@matheuscvp
