### ISSUE TITLE
Correções pontuais para a entrega

### ISSUE THREAD

**Issue by AmandaNbr** [Requisitos-de-Software/2021.2-AntennaPod#24]
## Descrição da Issue
Fazendo correções pontuais para a entrega

## Tasks:
- [x] Ajustes no cronograma
- [x] Arrumando tecnicas em ordem alfabetica

## Critérios de Aceitação:
- [x] Site atualizado e organizado
