### ISSUE TITLE
Melhoria do documento de priorização

### ISSUE THREAD

**Issue by yudi-azvd** [Requisitos-de-Software/2021.2-AntennaPod#26]
## Tasks:
- [x] Criar documento de priorização R$100
- [x] Esclarecer os intervalos dos preços
- [x] Esclarecer participantes e seus papeis
- [x] Barra lateral

## Critérios de Aceitação:
- [x] Documento criado
