### ISSUE TITLE
Criação de atas de reunião

### ISSUE THREAD

**Issue by Thais-ra** [Requisitos-de-Software/2021.2-AntennaPod#31]
## Descrição da Issue
As reuniões devem ser formalizadas a partir de atas.

## Tasks:
- [x] Criar um padrão para as atas
- [x] Registrar as atas passadas
- [x] Adicionar na wiki

**Comment by Thais-ra** [comment]
Ideia de modelo:
https://fga-eps-mds.github.io/2021.1-Pro-Especies-Docs/#/LeanInception/Meetings/31072021LeanInceptionPlanning
