### ISSUE TITLE
Melhorias entrega 2

### ISSUE THREAD

**Issue by AmandaNbr** [Requisitos-de-Software/2021.2-AntennaPod#36]
## Descrição da Issue
Realizar as melhorias levantadas na entrega 2

## Tasks:
- [x] Adicionar F e NF nos ids para identificar requisitos funcionais e não funcionais
- [x] Melhorar o cronograma (data estimada e data entregue)
- [x] Adicionar revisor no versionamento

## Critérios de Aceitação:
- [x] Todas as melhorias feitas.
