### ISSUE TITLE
Validação por Prototipação

### ISSUE THREAD

**Issue by matheuscvp** [Requisitos-de-Software/2021.2-AntennaPod#82]
## Descrição da Issue
Criar o documento que descreve a validação por prototipação feita pelo grupo

## Tasks:
- [ ] Criar o prototipo do AntennaPod
- [ ] Criar documento de validação por protoripação

## Critérios de Aceitação:
- [ ] Prototipo condizente com os requisitos modelados pelo grupo
- [ ] Documento descrevendo corretamente o que foi feito

## Assignees
@matheuscvp
