### ISSUE TITLE
Refatorar verificação de casos de uso

### ISSUE THREAD

**Issue by Thais-ra** [Requisitos-de-Software/2021.2-AntennaPod#94]
## Descrição da Issue
Alterar documento conforte os feedbacks do professor.

## Tasks:
- [ ] Adicionar metodologia de inspeção de Fagan
- [ ] Deixar claro como será feito o acompanhamento
- [x] Adicionar mais criterios ao check list
- [x] Adicionar grafico nos resultados
